App_Auth/urls.py
from django.urls import path
from . import views

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('signin/', views.signin_view, name='signin'),
    path('signout/', views.signout_view, name='signout'),
    path('404/', views.handle_not_found, name='404'),
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/update/', views.profile_update, name='profile_update'),

    path('admin-login/', views.admin_login_view, name='admin-login'),
    path('logout/', views.admin_logout_view, name='admin-logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('locations/', views.location_list, name='location_list'),
    path('locations/add/', views.add_location, name='add_location'),
    
    path('amenity/', views.amenity_list, name='amenity_list'),
    path('amenities/add/', views.add_amenity, name='add_amenity'),
    
    path('hotels/', views.hotel_list, name='hotel_list'),
    path('hotels/add/', views.add_hotel, name='add_hotel'),
    path('hotel/<int:hotel_id>/', views.hotel_detail, name='hotel_detail'), 
    
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/add/', views.add_room, name='add_room'),

    path('payments/', views.payment_list, name='payment_list'),
    path('payments/view/<int:pk>/', views.view_payment, name='view_payment'), 
    path('payments/update/<int:pk>/', views.update_payment, name='update_payment'),

    path('all-profiles/', views.view_profiles, name='profiles'),
]

App_Hotel/urls.py
from django.urls import path
from . import views

app_name = 'App_Hotel'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    # path('blog/', views.home, name='home'),

    path('findhotels/', views.hotel_list, name='hotel_list'),
    path('hotel/<int:pk>/', views.hotel_detail, name='hotel_detail'),

    path('cart/', views.cart, name='cart'),
    path('cart/remove/<int:booking_id>/', views.remove_booking, name='remove_booking'),

    path('payment/', views.payment, name='payment'),
    path('payment/confirmation/', views.payment_confirmation, name='payment_confirmation'),
    path('payment-list/', views.payments_list, name='payments_list'),

    path('wishlist/add/<int:hotel_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:hotel_id>/', views.remove_from_wishlist, name='remove_from_wishlist'), 
    path('wishlist/', views.wishlist_view, name='wishlist'),

    path('hotel/<int:pk>/submit_review/', views.submit_review, name='submit_review'),
    path('hotel/<int:review_id>/toggle_like/', views.toggle_like, name='toggle_like'),

]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_Auth.urls')),
    path('', include('App_Hotel.urls')),
    path('blog/', include('App_Blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

# handler404 = 'App_Auth.views.handle_not_found'

templates/layouts_hotel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <!-- Mirrored from www.ansonika.com/panagea/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Sep 2024 05:26:21 GMT -->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Domabooking - A Hotel Booking App"
    />
    <meta name="author" content="M3S" />
    <title>Hotel Booking App</title>

    <!-- Favicons-->
    <link
      rel="shortcut icon"
      href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
      type="image/x-icon"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="72x72"
      href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="114x114"
      href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="144x144"
      href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
    />

    <!-- GOOGLE WEB FONT -->
    <link rel="preconnect" href="https://fonts.gstatic.com/" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&amp;display=swap"
      rel="stylesheet"
    />

    <!-- BASE CSS -->
    <link href="{% static 'hotel_section/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'hotel_section/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'hotel_section/css/vendors.css' %}" rel="stylesheet" />

    <!-- CUSTOM CSS -->
    <link href="{% static 'hotel_section/css/custom.css' %}" rel="stylesheet" />

    <!-- ALTERNATIVE COLORS CSS -->
    <link href="#" id="colors" rel="stylesheet" />
  </head>

  <body class="datepicker_mobile_full">

    <div id="page">
      <!-- /header -->
	  {% include 'layouts_hotel/header.html' %}
      <main>
			
			<div class="">
				{% block content %}
				{% endblock %}
			</div>
      </main>
	  {% include 'layouts_hotel/footer.html' %}
    </div>

    <!-- Sign In Popup -->
    <div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide">
      <div class="small-dialog-header">
        <h3>Sign In</h3>
      </div>
      <form>
        <div class="sign-in-wrapper">
          <a href="#0" class="social_bt facebook">Login with Facebook</a>
          <a href="#0" class="social_bt google">Login with Google</a>
          <div class="divider"><span>Or</span></div>
          <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" id="email" />
            <i class="icon_mail_alt"></i>
          </div>
          <div class="form-group">
            <label>Password</label>
            <input
              type="password"
              class="form-control"
              name="password"
              id="password"
              value=""
            />
            <i class="icon_lock_alt"></i>
          </div>
          <div class="clearfix add_bottom_15">
            <div class="checkboxes float-start">
              <label class="container_check"
                >Remember me
                <input type="checkbox" />
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="float-end mt-1">
              <a id="forgot" href="javascript:void(0);">Forgot Password?</a>
            </div>
          </div>
          <div class="text-center">
            <input type="submit" value="Log In" class="btn_1 full-width" />
          </div>
          <div class="text-center">
            Don’t have an account? <a href="register.html">Sign up</a>
          </div>
          <div id="forgot_pw">
            <div class="form-group">
              <label>Please confirm login email below</label>
              <input
                type="email"
                class="form-control"
                name="email_forgot"
                id="email_forgot"
              />
              <i class="icon_mail_alt"></i>
            </div>
            <p>
              You will receive an email containing a link allowing you to reset
              your password to a new preferred one.
            </p>
            <div class="text-center">
              <input type="submit" value="Reset Password" class="btn_1" />
            </div>
          </div>
        </div>
      </form>
      <!--form -->
    </div>
    <!-- /Sign In Popup -->

    <div id="toTop"></div>
    <!-- Back to top button -->

    <!-- COMMON SCRIPTS -->
    <script src="{% static 'hotel_section/js/common_scripts.js' %}"></script>
    <script src="{% static 'hotel_section/js/main.js' %}"></script>
    <script src="{% static 'hotel_section/phpmailer/validate.js' %}"></script>

    <!-- DATEPICKER  -->
    <script>
      $(function () {
        "use strict";
        $('input[name="dates"]').daterangepicker({
          autoUpdateInput: false,
          minDate: new Date(),
          locale: {
            cancelLabel: "Clear",
          },
        });
        $('input[name="dates"]').on(
          "apply.daterangepicker",
          function (ev, picker) {
            $(this).val(
              picker.startDate.format("MM-DD-YY") +
                " > " +
                picker.endDate.format("MM-DD-YY")
            );
          }
        );
        $('input[name="dates"]').on(
          "cancel.daterangepicker",
          function (ev, picker) {
            $(this).val("");
          }
        );
      });
    </script>

    <!-- INPUT QUANTITY  -->
    <script src="{% static 'hotel_section/js/input_qty.js' %}"></script>

    <!-- COLOR SWITCHER  -->
    <script src="{% static 'hotel_section/js/switcher.js' %}"></script>
    <!-- <div id="style-switcher">
      <h6>
        Color Switcher <a href="#"><i class="ti-settings"></i></a>
      </h6>
      <div>
        <ul class="colors" id="color1">
          <li>
            <a href="#" class="default" title="Default"></a>
          </li>
          <li>
            <a href="#" class="aqua" title="Aqua"></a>
          </li>
          <li>
            <a href="#" class="green_switcher" title="Green"></a>
          </li>
          <li>
            <a href="#" class="orange" title="Orange"></a>
          </li>
          <li>
            <a href="#" class="blue" title="Blue"></a>
          </li>
          <li>
            <a href="#" class="beige" title="Beige"></a>
          </li>
          <li>
            <a href="#" class="gray" title="Gray"></a>
          </li>
          <li>
            <a href="#" class="green-2" title="Green"></a>
          </li>
          <li>
            <a href="#" class="navy" title="Navy"></a>
          </li>
          <li>
            <a href="#" class="peach" title="Peach"></a>
          </li>
          <li>
            <a href="#" class="purple" title="Purple"></a>
          </li>
          <li>
            <a href="#" class="red" title="Red"></a>
          </li>
          <li>
            <a href="#" class="violet" title="Violet"></a>
          </li>
        </ul>
      </div>
    </div> -->
  </body>
</html>

templates/layouts_hotel/footer.html
{% load static %}
<footer>
    <div class="container margin_60_35">
        <div class="row">
            <div class="col-lg-5 col-md-12 pe-5">
                <p><img src="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}" width="150" height="150" alt=""></p>
                <p>Mea nibh meis philosophia eu. Duis legimus efficiantur ea sea. Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu. Nihil facilisi indoctum an vix, ut delectus expetendis vis.</p>
                <div class="follow_us">
                    <ul>
                        <li>Follow us</li>
                        <li><a href="#0"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="#0"><i class="bi bi-twitter-x"></i></a></li>
                        <li><a href="#0"><i class="bi bi-instagram"></i></a></li>
                        <li><a href="#0"><i class="bi bi-tiktok"></i></a></li>
                        <li><a href="#0"><i class="bi bi-whatsapp"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 ms-lg-auto">
                <h5>Useful links</h5>
                <ul class="links">
                    <li><a href="{% url 'App_Hotel:about' %}">About</a></li>
                    <li><a href="{% url 'App_Auth:signin' %}">Signin</a></li>
                    <li><a href="{% url 'App_Auth:signup' %}">Signup</a></li>
                    <li><a href="{% url 'App_Hotel:faq' %}">FAQ</a></li>
                    <li><a href="{% url 'App_Hotel:contact' %}">Contacts</a></li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5>Contact with Us</h5>
                <ul class="contacts">
                    <li><a href="tel://61280932400"><i class="ti-mobile"></i> +880 1521 430255</a></li>
                    <li><a href="mailto:shovonmufrid98@gmail.com"><i class="ti-email"></i> info@m3s.com</a></li>
                </ul>
                <div id="newsletter">
                <h6>Newsletter</h6>
                <div id="message-newsletter"></div>
                <form method="post" action="https://www.ansonika.com/panagea/phpmailer/newsletter_template_email.php" name="newsletter_form" id="newsletter_form">
                    <div class="form-group">
                        <input type="email" name="email_newsletter" id="email_newsletter" class="form-control" placeholder="Your email">
                        <input type="submit" value="Submit" id="submit-newsletter">
                    </div>
                </form>
                </div>
            </div>
        </div>
        <!--/row-->
        <hr>
        <div class="row">
            <div class="col-lg-6">
                <ul id="footer-selector">
                    <li>
                        <div class="styled-select" id="lang-selector">
                            <select>
                                <option value="English" selected>English</option>
                                <option value="French">French</option>
                                <option value="Spanish">Spanish</option>
                                <option value="Russian">Russian</option>
                            </select>
                        </div>
                    </li>
                    <li>
                        <div class="styled-select" id="currency-selector">
                            <select>
                                <option value="Russian Ruble" selected>Russian Ruble</option>
                                <option value="US Dollar">US Dollar</option>
                            </select>
                        </div>
                    </li>
                    <li><img src="{% static 'hotel_section/img/cards_all.svg' %}" alt=""></li>
                </ul>
            </div>
            <div class="col-lg-6">
                <ul id="additional_links">
                    <li><a href="#0">Terms and conditions</a></li>
                    <li><a href="#0">Privacy</a></li>
                    <li><span>© m3s</span></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/layouts_hotel/header.html
{% load static %}
<header class="header menu_fixed">
    <div id="preloader"><div data-loader="circle-side"></div></div><!-- /Page Preload -->
    <div id="logo">
        <a href="{% url 'App_Hotel:home' %}">
            <img src="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}" width="100" height="100" alt="" class="logo_normal">
            <img src="{% static 'hotel_section/img/Icon/logo.png' %}" width="100" height="100" alt="" class="logo_sticky">
        </a>
    </div>
    <ul id="top_menu">
        <li><a href="{% url 'App_Hotel:cart' %}" class="cart-menu-btn" title="Cart">
            <!-- <strong>4</strong> -->
        </a></li>


        <li><a href="{% url 'App_Hotel:wishlist' %}" class="wishlist_bt_top" title="Your wishlist">Your wishlist</a></li>
    </ul>
    <!-- /top_menu -->
    <a href="#menu" class="btn_mobile">
        <div class="hamburger hamburger--spin" id="hamburger">
            <div class="hamburger-box">
                <div class="hamburger-inner"></div>
            </div>
        </div>
    </a>
    <nav id="menu" class="main-menu" style="margin: 0 50px;">
        <ul>
            <li><span><a href="{% url 'App_Hotel:home' %}">Home</a></span>
                <!-- <ul>
                    <li><a href="index.html">Home Default</a></li>	
                </ul> -->
            </li>
            
            <li><span><a href="{% url 'App_Hotel:hotel_list' %}">Find Hotels</a></span>
                <!-- <ul>
                    <li>
                        <span><a href="#0">Hotel Grid</a></span>
                        <ul>
                            <li><a href="hotels-grid-sidebar.html">Hotel Grid Sidebar</a></li>
                        </ul>
                    </li>
                    <li><a href="hotel-detail.html">Hotel Detail</a></li>
                </ul> -->
            </li>
            <li>
                <span><a href="{% url 'App_Hotel:about' %}">About</a></span>
            </li>
            <li>
                <span><a href="{% url 'App_Hotel:contact' %}">Contact Us</a></span>
            </li>
            <li>
                <span><a href="{% url 'App_Hotel:faq' %}">FAQ</a></span>
            </li>

            <li><span><a href="#0">Profile</a></span>
                <ul>
                    {% if user.is_authenticated %}
                        <li style="color: black;">
                            <a href="{% url 'App_Auth:profile_view' %}" href="">{{ user.email }}</a>
                        </li>    
                        <li style="color: black;">
                            <a href="{% url 'App_Hotel:cart' %}" href="">My Cart</a>
                        </li>  
                        <li style="color: black;">
                            <a href="{% url 'App_Hotel:payments_list' %}" href="">All Payments</a>
                        </li>      
                        <li style="color: black;">
                            <a href="{% url 'App_Hotel:wishlist' %}" href="">My Wishlist</a>
                        </li>    
                        <li style="color: black;"> 
                            <a href="{% url 'App_Auth:signout' %}" href="">Signout</a>
                        </li>
                    {% else %}
                        <li style="color: black;"> 
                            <a href="{% url 'App_Auth:signin' %}"  class="login" title="Sign In">Sign In</a>
                        </li>
                        <li style="color: black;"> 
                            <a href="{% url 'App_Auth:signup' %}"  class="login" title="Sign In">Sign Up</a>
                        </li>
                    {% endif %}

                </ul>
            </li>
        </ul>
    </nav>
</header>