App_Auth/urls.py
from django.urls import path
from . import views

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('signin/', views.signin_view, name='signin'),
    path('signout/', views.signout_view, name='signout'),
    path('404/', views.handle_not_found, name='404'),
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/update/', views.profile_update, name='profile_update'),

    path('admin-login/', views.admin_login_view, name='admin-login'),
    path('logout/', views.admin_logout_view, name='admin-logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('locations/', views.location_list, name='location_list'),
    path('locations/add/', views.add_location, name='add_location'),
    
    path('amenity/', views.amenity_list, name='amenity_list'),
    path('amenities/add/', views.add_amenity, name='add_amenity'),
    
    path('hotels/', views.hotel_list, name='hotel_list'),
    path('hotels/add/', views.add_hotel, name='add_hotel'),
    path('hotel/<int:hotel_id>/', views.hotel_detail, name='hotel_detail'), 
    
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/add/', views.add_room, name='add_room'),

    path('payments/', views.payment_list, name='payment_list'),
    path('payments/view/<int:pk>/', views.view_payment, name='view_payment'), 
    path('payments/update/<int:pk>/', views.update_payment, name='update_payment'),

    path('all-profiles/', views.view_profiles, name='profiles'),
]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('App_Auth.urls')),
    path('', include('App_Hotel.urls')),
    path('blog/', include('App_Blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

# handler404 = 'App_Auth.views.handle_not_found'

templates/layouts_admin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <!-- Mirrored from www.ansonika.com/panagea/admin_section/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Sep 2024 05:27:52 GMT -->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="M3S" />
    <title>Hotel Booking | Dashboard</title>

    <!-- Favicons-->
    <!-- <link rel="shortcut icon" href="{% static 'admin_section/vendor/jquery/jquery.min.js' %}" type="image/x-icon" />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      href="{% static 'admin_section/vendor/jquery/jquery.min.js' %}"
    /> -->
    <link
    rel="apple-touch-icon"
    type="image/x-icon"
    href="{% static 'hotel_section/img/Icon/logo.png' %}"
    /> 
    <link
    rel="shortcut icon"
    href="{% static 'hotel_section/img/Icon/logo-rmbg.png' %}"
    type="image/x-icon"
  />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="72x72"
      href="{% static 'admin_section/vendor/jquery/jquery.min.js' %}"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="114x114"
      href="{% static 'admin_section/vendor/jquery/jquery.min.js' %}"
    />
    <link
      rel="apple-touch-icon"
      type="image/x-icon"
      sizes="144x144"
      href="{% static 'admin_section/vendor/jquery/jquery.min.js' %}"
    />

    <!-- GOOGLE WEB FONT -->
    <link rel="preconnect" href="https://fonts.gstatic.com/" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&amp;display=swap"
      rel="stylesheet"
    />

    <!-- Bootstrap core CSS-->
    <link href="{% static 'admin_section/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Main styles -->
    <link href="{% static 'admin_section/css/admin.css' %}" rel="stylesheet" />
    <!-- Icon fonts-->
    <link
      href="{% static 'admin_section/vendor/font-awesome/css/font-awesome.min.css' %}"
      rel="stylesheet"
    />
    <!-- Plugin styles -->
    <link href="{% static 'admin_section/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" />
    <!-- Your custom styles -->
    <link href="{% static 'admin_section/css/custom.css' %}" rel="stylesheet" />
  </head>

  <body class="fixed-nav sticky-footer" id="page-top">
    <!-- Navigation-->
    {% include 'layouts_admin/navigation.html' %}
    <!-- /Navigation-->

    <div class="content-wrapper">
        <div class="container-fluid">
            <!-- Breadcrumbs-->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'App_Auth:dashboard' %}">Admin</a>
                </li>
                <li class="breadcrumb-item active">
                    {% block route %}
                   
                    {% endblock %}
                </li>
            </ol>
            <!-- Breadcrumbs-->

            {% block content %}

            {% endblock %}
        </div>
      <!-- /.container-fluid-->
    </div>
    {% include 'layouts_admin/footer.html' %}

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button
                    class="close"
                    type="button"
                    data-dismiss="modal"
                    aria-label="Close"
                    >
                    <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Select "Logout" below if you are ready to end your current session.
                </div>
                <div class="modal-footer">
                    <button
                    class="btn btn-secondary"
                    type="button"
                    data-dismiss="modal"
                    >
                    Cancel
                    </button>
                    <a class="btn btn-primary" href="{% url 'App_Auth:admin-logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'admin_section/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'admin_section/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'admin_section/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'admin_section/vendor/chart.js/Chart.js' %}"></script>
    <script src="{% static 'admin_section/vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'admin_section/vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'admin_section/vendor/jquery.magnific-popup.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'admin_section/js/admin.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'admin_section/js/admin-charts.js' %}"></script>
  </body>

  <!-- Mirrored from www.ansonika.com/panagea/admin_section/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Sep 2024 05:28:00 GMT -->
</html>

templates/layouts_admin/footer.html
<footer class="sticky-footer">
    <div class="container">
      <div class="text-center">
        <small>Copyright © m3s 2024</small>
      </div>
    </div>
  </footer>

templates/layouts_admin/navigation.html
{% load static %}
<nav
  class="navbar navbar-expand-lg navbar-dark bg-default fixed-top"
  id="mainNav"
>
 
  <a class="navbar-brand" href="{% url 'App_Auth:dashboard' %}" >
    <!-- <img src="{% static 'hotel_section/img/Icon/logoadmin.png' %}" width="200" height="50" alt=""> -->
  <p style="height: 7px;">Admin Panel</p>
  </a>
  <button
    class="navbar-toggler navbar-toggler-right"
    type="button"
    data-toggle="collapse"
    data-target="#navbarResponsive"
    aria-controls="navbarResponsive"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Dashboard"
      >
        <a class="nav-link" href="{% url 'App_Auth:dashboard' %}">
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">Dashboard</span>
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Messages"
      >
        <a class="nav-link" href="{% url 'App_Auth:amenity_list' %}">
          <i class="fa fa-fw fa-envelope-open"></i>
          <span class="nav-link-text">Amenity</span>
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title=""
        data-original-title="Bookings"
      >
        <a class="nav-link" href="{% url 'App_Auth:location_list' %}">
          <i class="fa fa-fw fa-calendar-check-o"></i>
          <span class="nav-link-text"
            >Location
            <!-- <span class="badge badge-pill badge-primary">6 New</span></span -->
          
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="My listings"
      >
        <a
          class="nav-link nav-link-collapse collapsed"
          data-toggle="collapse"
          href="#collapseMylistings"
        >
          <i class="fa fa-fw fa-list"></i>
          <span class="nav-link-text">My listings</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseMylistings">
          <li>
            <a href="listings.html"
              >Pending <span class="badge badge-pill badge-primary">6</span></a
            >
          </li>
          <li>
            <a href="listings.html"
              >Active <span class="badge badge-pill badge-success">6</span></a
            >
          </li>
          <li>
            <a href="listings.html"
              >Expired <span class="badge badge-pill badge-danger">6</span></a
            >
          </li>
        </ul>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Reviews"
      >
        <a class="nav-link" href="{% url 'App_Auth:hotel_list' %}">
          <i class="fa fa-fw fa-star"></i>
          <span class="nav-link-text">Hotels</span>
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Bookmarks"
      >
        <a class="nav-link" href="{% url 'App_Auth:room_list' %}">
          <i class="fa fa-fw fa-heart"></i>
          <span class="nav-link-text">Rooms</span>
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Add listing"
      >
        <a class="nav-link" href="{% url 'App_Auth:payment_list' %}">
          <i class="fa fa-fw fa-plus-circle"></i>
          <span class="nav-link-text">All Payments</span>
        </a>
      </li>
      <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="My profile"
      >
        <a class="nav-link" href="{% url 'App_Auth:profiles' %}">
          <i class="fa fa-fw fa-user"></i>
          <span class="nav-link-text">All Profiles</span>
        </a>
      </li>
      <!-- <li
        class="nav-item"
        data-toggle="tooltip"
        data-placement="right"
        title="Components"
      >
        <a
          class="nav-link nav-link-collapse collapsed"
          data-toggle="collapse"
          href="#collapseComponents"
        >
          <i class="fa fa-fw fa-gear"></i>
          <span class="nav-link-text">Components</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseComponents">
          <li>
            <a href="charts.html">Charts</a>
          </li>
          <li>
            <a href="tables.html">Tables</a>
          </li>
        </ul>
      </li> -->
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <!-- <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle mr-lg-2"
          id="messagesDropdown"
          href="#"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <i class="fa fa-fw fa-envelope"></i>
          <span class="d-lg-none"
            >Messages
            <span class="badge badge-pill badge-primary">12 New</span>
          </span>
          <span class="indicator text-primary d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">New Messages:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>David Miller</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              Hey there! This new version of SB Admin is pretty awesome! These
              messages clip off when they reach the end of the box so they don't
              overflow over to the sides!
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>Jane Smith</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              I was wondering if you could meet for an appointment at 3:00
              instead of 4:00. Thanks!
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>John Doe</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              I've sent the final files over to you for review. When you're able
              to sign off of them let me know and we can discuss distribution.
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all messages</a>
        </div>
      </li> -->
      <!-- <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle mr-lg-2"
          id="alertsDropdown"
          href="#"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <i class="fa fa-fw fa-bell"></i>
          <span class="d-lg-none"
            >Alerts
            <span class="badge badge-pill badge-warning">6 New</span>
          </span>
          <span class="indicator text-warning d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">New Alerts:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong
              >
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              This is an automated server response message. All systems are
              online.
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-danger">
              <strong>
                <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong
              >
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              This is an automated server response message. All systems are
              online.
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong
              >
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">
              This is an automated server response message. All systems are
              online.
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all alerts</a>
        </div>
      </li> -->
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0 mr-lg-2">
          <div class="input-group">
            <input
              class="form-control search-top"
              type="text"
              placeholder="Search for..."
            />
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>Logout</a
        >
      </li>
    </ul>
  </div>
</nav>